<?php

namespace Database\Seeders;

use App\Models\Reservation;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReservationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $reservations = [
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ],
            [
                'customerName' => "テスト",
                'customerMail' => "テスト",
                'customerAddress' => "testtest0001",
                'countryName' => "北海道",
                'room_info_id' => 180,
                'firstDate' => "2023-05-15",
                'lastDate' => "2023-05-15",
                'discountCode' => "-",
                'paymentFlag' => 0,
            ]
        ];

        //一括登録
        foreach ($reservations as $reservation) {
            Reservation::create($reservation);
        }
    }
}
