<?php

namespace Database\Seeders;

use App\Models\Room_info;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Room_infoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $roomInfos = [
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 114,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 114,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 115,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 115,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 116,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 116,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 117,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 117,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 118,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 118,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 119,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 119,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 120,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 120,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 121,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 121,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 122,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 122,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 123,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 123,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 124,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 124,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 125,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 125,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 126,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 126,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 127,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 127,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 128,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 128,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 129,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 129,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 130,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 130,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 131,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 131,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 132,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 132,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 133,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 133,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 134,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 134,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 135,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 135,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 135,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 136,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 136,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 137,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 137,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 138,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 138,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 139,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 140,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 141,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 141,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 142,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 142,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 143,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 143,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 144,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 144,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 145,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 145,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 146,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 147,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 147,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 148,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 149,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 150,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 151,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 151,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 152,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 152,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 153,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 153,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 154,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 154,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 155,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 155,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 156,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 156,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 157,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 158,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 158,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 159,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 159,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 160,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 161,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 162,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 163,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 163,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 164,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 164,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 165,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 165,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 166,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 167,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 168,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 169,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 169,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 170,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 170,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 170,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 171,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 171,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 172,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 173,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 173,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 174,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 175,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 175,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 176,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 176,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 177,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 177,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 178,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 178,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 179,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 179,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 180,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 180,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 181,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 181,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 182,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 182,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 183,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 184,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 184,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 185,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 185,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 186,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 187,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 187,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 188,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 189,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 190,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 191,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 192,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 192,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 193,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 194,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 195,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 196,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 197,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 198,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 199,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 200,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 201,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 201,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 202,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 10000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 203,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 20000,
                'tax_id' => 4,
                'roomCount' => 25,
                'hotel_id' => 204,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 25000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 205,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 30000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 206,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 40000,
                'tax_id' => 4,
                'roomCount' => 10,
                'hotel_id' => 207,
            ],
            [
                'roomName' => "テストルーム",
                'roomFee' => 50000,
                'tax_id' => 4,
                'roomCount' => 5,
                'hotel_id' => 208,
            ]
        ];

        //一括登録
        foreach ($roomInfos as $roomInfo) {
            Room_info::create($roomInfo);
        }
    }
}
